import type { Paginated } from '@/types/admin'
import type { AddInquiryNoteRequest, AdminInquiryDetail, AdminInquiryListItem, AdminInquiryListQuery, UpdateInquiryPriorityRequest, UpdateInquiryStatusRequest } from '@/types/inquiryAdmin'
const ADMIN_API_BASE = import.meta.env.VITE_ADMIN_API_BASE ?? '/api'
type ApiResponse<T> = { ok:true; data:T; meta?:unknown } | { ok:false; error:{ code:string; message:string } }
function qs(query:AdminInquiryListQuery={}):string{ const p=new URLSearchParams(); if(query.status&&query.status!=='all') p.set('status',query.status); if(query.priority&&query.priority!=='all') p.set('priority',query.priority); if(query.category) p.set('category',query.category); if(query.search) p.set('search',query.search); if(query.limit) p.set('limit',String(query.limit)); if(query.offset) p.set('offset',String(query.offset)); const out=p.toString(); return out?`?${out}`:'' }
async function req<T>(path:string, init?:RequestInit):Promise<T>{ const response=await fetch(`${ADMIN_API_BASE}${path}`,{ credentials:'include', headers:{ 'content-type':'application/json', ...(init?.headers??{}) }, ...init }); const payload=await response.json() as ApiResponse<T>; if(!response.ok || !payload.ok) throw new Error(payload.ok?`Admin API request failed: ${response.status}`:payload.error.message); return payload.data }
export function fetchAdminInquiries(query:AdminInquiryListQuery={}):Promise<Paginated<AdminInquiryListItem>>{ return req(`/inquiries${qs(query)}`) }
export function fetchAdminInquiryDetail(id:string):Promise<AdminInquiryDetail>{ return req(`/inquiries/${encodeURIComponent(id)}`) }
export function updateAdminInquiryStatus(id:string,input:UpdateInquiryStatusRequest):Promise<{ inquiryId:string; status:string; eventId:string }>{ return req(`/inquiries/${encodeURIComponent(id)}/status`,{ method:'PATCH', body:JSON.stringify(input) }) }
export function updateAdminInquiryPriority(id:string,input:UpdateInquiryPriorityRequest):Promise<{ inquiryId:string; priority:string; eventId:string }>{ return req(`/inquiries/${encodeURIComponent(id)}/priority`,{ method:'PATCH', body:JSON.stringify(input) }) }
export function addAdminInquiryNote(id:string,input:AddInquiryNoteRequest):Promise<{ inquiryId:string; eventId:string }>{ return req(`/inquiries/${encodeURIComponent(id)}/events`,{ method:'POST', body:JSON.stringify(input) }) }
