<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import type { LoadedMarkdownPage } from '@/markdown/types'
import ProductCard from './ProductCard.vue'
import { filterProductCatalogEntries, getAvailableProductCategories, getAvailableProductCollections, getAvailableProductStatuses, getAvailableProductSubcategories, getAvailableProductTags, getAvailableProductTypes, getProductCatalogEntries, sortProductCatalogEntries, type ProductCatalogSort } from '@/utils/productCatalog'
import { resolveProductCategoryLabel, resolveProductCollectionLabel, resolveProductSubcategoryLabel, resolveProductTypeLabel } from '@/utils/storeTaxonomy'
import { formatProductStatus } from '@/utils/formatProduct'
const SORT_OPTIONS: { value: ProductCatalogSort; label: string }[] = [ { value: 'order', label: '기본순' }, { value: 'newest', label: '최근 출시순' }, { value: 'oldest', label: '오래된순' }, { value: 'title', label: '이름순' }, { value: 'price-low', label: '낮은 가격순' }, { value: 'price-high', label: '높은 가격순' } ]
const props = withDefaults(defineProps<{ pages?: LoadedMarkdownPage[]; title?: string; intro?: string; limit?: number; showUnavailable?: boolean; showCategoryFilter?: boolean; showSubcategoryFilter?: boolean; showCollectionFilter?: boolean; defaultStatus?: string; defaultType?: string; defaultCategory?: string; defaultSubcategory?: string; defaultCollection?: string; defaultTag?: string; defaultQuery?: string; defaultSort?: ProductCatalogSort | string; emptyTitle?: string; emptyBody?: string }>(), { pages: () => [], title: '상품 카탈로그', intro: '', limit: 48, showUnavailable: true, showCategoryFilter: true, showSubcategoryFilter: false, showCollectionFilter: true, defaultStatus: 'all', defaultType: 'all', defaultCategory: 'all', defaultSubcategory: 'all', defaultCollection: 'all', defaultTag: 'all', defaultQuery: '', defaultSort: 'order', emptyTitle: '상품이 없습니다', emptyBody: '필터 조건을 바꾸거나 전체 상품으로 돌아가세요.' })
function normalizeSort(value: string): ProductCatalogSort { return SORT_OPTIONS.some((option) => option.value === value) ? (value as ProductCatalogSort) : 'order' }
const query = ref(props.defaultQuery); const statusFilter = ref(props.defaultStatus || 'all'); const typeFilter = ref(props.defaultType || 'all'); const categoryFilter = ref(props.defaultCategory || 'all'); const subcategoryFilter = ref(props.defaultSubcategory || 'all'); const collectionFilter = ref(props.defaultCollection || 'all'); const tagFilter = ref(props.defaultTag || 'all'); const sortMode = ref<ProductCatalogSort>(normalizeSort(String(props.defaultSort || 'order')))
watch(() => [props.defaultQuery, props.defaultStatus, props.defaultType, props.defaultCategory, props.defaultSubcategory, props.defaultCollection, props.defaultTag, props.defaultSort], () => { query.value = props.defaultQuery; statusFilter.value = props.defaultStatus || 'all'; typeFilter.value = props.defaultType || 'all'; categoryFilter.value = props.defaultCategory || 'all'; subcategoryFilter.value = props.defaultSubcategory || 'all'; collectionFilter.value = props.defaultCollection || 'all'; tagFilter.value = props.defaultTag || 'all'; sortMode.value = normalizeSort(String(props.defaultSort || 'order')) })
const entries = computed(() => getProductCatalogEntries(props.pages)); const statuses = computed(() => getAvailableProductStatuses(entries.value)); const types = computed(() => getAvailableProductTypes(entries.value)); const categories = computed(() => getAvailableProductCategories(entries.value)); const subcategories = computed(() => getAvailableProductSubcategories(entries.value)); const collections = computed(() => getAvailableProductCollections(entries.value)); const tags = computed(() => getAvailableProductTags(entries.value)); const limit = computed(() => Math.max(1, Math.min(96, Math.floor(props.limit || 48)))); const shouldShowSubcategoryFilter = computed(() => props.showSubcategoryFilter && subcategories.value.length > 0)
const filteredEntries = computed(() => sortProductCatalogEntries(filterProductCatalogEntries(entries.value, { query: query.value, status: statusFilter.value, type: typeFilter.value, category: categoryFilter.value, subcategory: subcategoryFilter.value, collection: collectionFilter.value, tag: tagFilter.value, showUnavailable: props.showUnavailable }), sortMode.value))
const visibleEntries = computed(() => filteredEntries.value.slice(0, limit.value)); const hasActiveFilters = computed(() => Boolean(query.value.trim()) || statusFilter.value !== 'all' || typeFilter.value !== 'all' || categoryFilter.value !== 'all' || subcategoryFilter.value !== 'all' || collectionFilter.value !== 'all' || tagFilter.value !== 'all'); const summary = computed(() => `${visibleEntries.value.length} / ${filteredEntries.value.length}개 표시`)
function clearFilters() { query.value = ''; statusFilter.value = 'all'; typeFilter.value = 'all'; categoryFilter.value = 'all'; subcategoryFilter.value = 'all'; collectionFilter.value = 'all'; tagFilter.value = 'all'; sortMode.value = 'order' }
</script>
<template>
  <section class="vt-product-catalog" aria-labelledby="product-catalog-title">
    <header class="vt-product-catalog__header"><div><h2 id="product-catalog-title" class="vt-product-catalog__title">{{ title }}</h2><p v-if="intro" class="vt-product-catalog__intro">{{ intro }}</p></div><p class="vt-product-catalog__summary" aria-live="polite">{{ summary }}</p></header>
    <div class="vt-product-catalog__toolbar" aria-label="상품 필터">
      <label class="vt-product-catalog__field vt-product-catalog__field--search"><span class="vt-product-catalog__label">검색</span><input v-model="query" class="vt-product-catalog__search" type="search" placeholder="상품명, 카테고리, 컬렉션, 태그 검색" autocomplete="off" /></label>
      <label v-if="showCategoryFilter" class="vt-product-catalog__field"><span class="vt-product-catalog__label">카테고리</span><select v-model="categoryFilter" class="vt-product-catalog__select"><option value="all">전체 카테고리</option><option v-for="category in categories" :key="category" :value="category">{{ resolveProductCategoryLabel(category) }}</option></select></label>
      <label class="vt-product-catalog__field"><span class="vt-product-catalog__label">유형</span><select v-model="typeFilter" class="vt-product-catalog__select"><option value="all">전체 유형</option><option v-for="type in types" :key="type" :value="type">{{ resolveProductTypeLabel(type) }}</option></select></label>
      <label v-if="showCollectionFilter" class="vt-product-catalog__field"><span class="vt-product-catalog__label">컬렉션</span><select v-model="collectionFilter" class="vt-product-catalog__select"><option value="all">전체 컬렉션</option><option v-for="collection in collections" :key="collection" :value="collection">{{ resolveProductCollectionLabel(collection) }}</option></select></label>
      <label v-if="shouldShowSubcategoryFilter" class="vt-product-catalog__field"><span class="vt-product-catalog__label">세부 매대</span><select v-model="subcategoryFilter" class="vt-product-catalog__select"><option value="all">전체 세부 매대</option><option v-for="subcategory in subcategories" :key="subcategory" :value="subcategory">{{ resolveProductSubcategoryLabel(subcategory) }}</option></select></label>
      <label class="vt-product-catalog__field"><span class="vt-product-catalog__label">상태</span><select v-model="statusFilter" class="vt-product-catalog__select"><option value="all">전체 상태</option><option v-for="status in statuses" :key="status" :value="status">{{ formatProductStatus(status) }}</option></select></label>
      <label class="vt-product-catalog__field"><span class="vt-product-catalog__label">태그</span><select v-model="tagFilter" class="vt-product-catalog__select"><option value="all">전체 태그</option><option v-for="tag in tags" :key="tag" :value="tag">{{ tag }}</option></select></label>
      <label class="vt-product-catalog__field"><span class="vt-product-catalog__label">정렬</span><select v-model="sortMode" class="vt-product-catalog__select"><option v-for="option in SORT_OPTIONS" :key="option.value" :value="option.value">{{ option.label }}</option></select></label>
      <button class="vt-product-catalog__clear" type="button" :disabled="!hasActiveFilters" @click="clearFilters">필터 초기화</button>
    </div>
    <div v-if="visibleEntries.length" class="vt-product-catalog__grid"><ProductCard v-for="entry in visibleEntries" :key="entry.slug" :item="entry" /></div>
    <article v-else class="vt-product-catalog__empty" aria-live="polite"><strong>{{ emptyTitle }}</strong><p>{{ emptyBody }}</p><button v-if="hasActiveFilters" class="vt-product-catalog__clear vt-product-catalog__clear--empty" type="button" @click="clearFilters">전체 상품 보기</button></article>
  </section>
</template>
