<script setup lang="ts">
import { computed,onBeforeUnmount,onMounted,ref,watch } from 'vue'
import { SegmentedPlaybackSession } from '@/lib/media/segmentedPlaybackSession'
type VideoRatio='auto'|'16/9'|'4/3'|'1/1'|'9/16';type VideoFit='contain'|'cover'
const props=withDefaults(defineProps<{streamManifestUrl:string;title?:string;poster?:string;playsInline?:boolean;ratio?:VideoRatio;fit?:VideoFit;breakout?:boolean;manifestWidth?:number;manifestHeight?:number;duration?:number}>(),{title:'',poster:'',playsInline:true,ratio:'auto',fit:'contain',breakout:false})
const videoRef=ref<HTMLVideoElement|null>(null),rootRef=ref<HTMLElement|null>(null),isPlaying=ref(false),currentTime=ref(0),duration=ref(0),session=ref<SegmentedPlaybackSession|null>(null),started=ref(false),error=ref('')
const ratio=computed(()=>props.manifestWidth&&props.manifestHeight?`${props.manifestWidth} / ${props.manifestHeight}`:props.ratio==='9/16'?'9 / 16':props.ratio==='4/3'?'4 / 3':props.ratio==='1/1'?'1 / 1':'16 / 9')
const formatted=computed(()=>`${fmt(currentTime.value)} / ${fmt(duration.value||props.duration||0)}`);function fmt(v:number){const n=Number.isFinite(v)&&v>0?v:0;return `${Math.floor(n/60)}:${String(Math.floor(n%60)).padStart(2,'0')}`}
function ensure(){if(!videoRef.value)throw new Error('E_PUBLIC_VIDEO_ELEMENT_MISSING');if(!session.value)session.value=new SegmentedPlaybackSession(videoRef.value,props.streamManifestUrl);return session.value}
async function toggle(){error.value='';try{if(!started.value||videoRef.value?.paused){await ensure().explicitPlay();started.value=true;isPlaying.value=true}else{ensure().pause();isPlaying.value=false}}catch(e){error.value=e instanceof Error?e.message:String(e)}}
async function seek(e:Event){const t=Number((e.target as HTMLInputElement).value);if(!Number.isFinite(t))return;currentTime.value=t;try{await ensure().seek(t)}catch(err){error.value=err instanceof Error?err.message:String(err)}}
function time(){const v=videoRef.value;if(!v)return;currentTime.value=v.currentTime||0;if(Number.isFinite(v.duration)&&v.duration>0)duration.value=v.duration;void session.value?.pump()}
let observer:IntersectionObserver|null=null
onMounted(()=>{if(rootRef.value){observer=new IntersectionObserver((entries)=>{const e=entries[0];if(started.value&&e&&!e.isIntersecting){setTimeout(()=>{if(started.value&&!observerEntryVisible){session.value?.outOfView();isPlaying.value=false}},250)};observerEntryVisible=Boolean(e?.isIntersecting)},{threshold:0.01});observer.observe(rootRef.value)}});let observerEntryVisible=true
onBeforeUnmount(()=>{observer?.disconnect();session.value?.destroy()});watch(()=>props.streamManifestUrl,()=>{session.value?.destroy();session.value=null;started.value=false;isPlaying.value=false})
</script>
<template><figure ref="rootRef" class="vt-video-player" :class="{ 'vt-media-breakout': props.breakout }" :style="{ '--vt-video-ratio': ratio, '--vt-video-fit': props.fit }"><div v-if="props.streamManifestUrl" class="vt-video-player__stage"><div class="vt-video-player__clip" role="button" tabindex="0" :aria-label="props.title || 'Video'" @click="toggle" @keydown.enter.prevent="toggle" @keydown.space.prevent="toggle"><video ref="videoRef" class="vt-video-player__video" :poster="props.poster||undefined" :playsinline="props.playsInline" preload="none" @timeupdate="time" @play="isPlaying=true" @pause="isPlaying=false" @ended="isPlaying=false"></video><div class="vt-video-player__custom-controls" @click.stop @pointerdown.stop><button type="button" class="vt-video-player__control-button" @click.stop="toggle">{{ isPlaying ? 'Ⅱ' : '▶' }}</button><span class="vt-video-player__time">{{ formatted }}</span><input class="vt-video-player__progress" type="range" min="0" :max="duration||props.duration||0" step="0.01" :value="currentTime" @input="seek" @click.stop @keydown.stop></div></div></div><div v-else class="vt-video-player__unsupported">Video stream is unavailable.</div><p v-if="error" class="vt-video-player__error">{{ error }}</p><figcaption v-if="props.title" class="vt-video-player__caption">{{ props.title }}</figcaption></figure></template>
<style scoped>
.vt-video-player{--vt-video-ratio:16/9;--vt-video-fit:contain;width:min(100%,var(--vt-video-frame-max-width,720px));margin-inline:auto}.vt-video-player__stage{position:relative;width:100%;aspect-ratio:var(--vt-video-ratio);overflow:visible}.vt-video-player__clip{position:absolute;inset:1px;overflow:hidden;border-radius:1.5px;cursor:pointer}.vt-video-player__video{position:absolute;inset:0;width:100%;height:100%;object-fit:var(--vt-video-fit);background:transparent}.vt-video-player__custom-controls{position:absolute;left:10px;right:10px;bottom:10px;z-index:2;display:grid;grid-template-columns:auto auto minmax(0,1fr);align-items:center;gap:8px;padding:7px 9px;border-radius:999px;background:color-mix(in srgb,#111 62%,transparent);backdrop-filter:blur(8px)}.vt-video-player__control-button{border:0;border-radius:999px;width:28px;height:28px;cursor:pointer}.vt-video-player__time{color:#fff;font-size:.76rem;white-space:nowrap}.vt-video-player__progress{width:100%;min-width:0}.vt-video-player__unsupported,.vt-video-player__error{padding:1rem;opacity:.75}.vt-video-player__caption{margin-top:.65rem;font-size:.86rem}
</style>
