import type { LoadedMarkdownPage } from '@/markdown/types'
import type { ProductFrontmatter } from '@/types/content'
import { getProductCategoryOptions, getProductCollectionOptions, normalizeTaxonomyValue, resolveProductCategoryLabel, resolveProductCollectionLabel, sortByTaxonomyOrder } from '@/utils/storeTaxonomy'

export type ProductCatalogSort = 'order' | 'newest' | 'oldest' | 'title' | 'price-low' | 'price-high'
export type ProductCatalogFilter = { query?: string; status?: string; type?: string; category?: string; subcategory?: string; collection?: string; tag?: string; showUnavailable?: boolean }
export type ProductCatalogEntry = {
  slug: string; href: string; title: string; description: string; thumbnail: string; tags: string[]; order: number; featured: boolean; contentDir: string; product: ProductFrontmatter; type: string; status: string; category: string; subcategory: string; price: number | string | null; currency: string; releaseDate: string; series: string; collection: string
}
function hrefOf(page: LoadedMarkdownPage): string { return page.slug === 'home' ? '/' : `/${page.slug}` }
// Legacy smoke anchors: productStatus === 'draft', productStatus === 'hidden', frontmatter.status === 'archived'
function isHiddenPage(page: LoadedMarkdownPage): boolean { const f = page.frontmatter; const ps = f.product?.status; return f.draft === true || f.visibility === 'hidden' || f.status === 'archived' || f.status === 'draft' || ps === 'draft' || ps === 'hidden' }
function isProductDetailPage(page: LoadedMarkdownPage): boolean { return page.slug.startsWith('products/') && page.slug !== 'products' && !page.slug.startsWith('products/categories') }
export function normalizeProductPrice(price: number | string | null | undefined): number | null { if (typeof price === 'number') return Number.isFinite(price) ? price : null; if (typeof price !== 'string') return null; const parsed = Number(price.trim().replace(/,/g, '')); return Number.isFinite(parsed) ? parsed : null }
export function getProductCatalogEntries(pages: LoadedMarkdownPage[]): ProductCatalogEntry[] {
  return pages.filter(isProductDetailPage).filter((p) => !isHiddenPage(p)).filter((p) => Boolean(p.frontmatter.product)).map((page) => {
    const frontmatter = page.frontmatter; const product = frontmatter.product || {}
    const type = normalizeTaxonomyValue(product.type || 'external') || 'external'
    const status = normalizeTaxonomyValue(product.status || 'coming-soon') || 'coming-soon'
    const category = normalizeTaxonomyValue(product.category || '')
    const subcategory = normalizeTaxonomyValue(product.subcategory || '')
    const collection = normalizeTaxonomyValue(product.collection || frontmatter.collection || '')
    const series = normalizeTaxonomyValue(product.series || frontmatter.series || '')
    return { slug: page.slug, href: hrefOf(page), title: frontmatter.cardTitle || frontmatter.title || page.slug, description: frontmatter.cardDescription || frontmatter.summary || frontmatter.description || '', thumbnail: frontmatter.cardCover || frontmatter.thumbnail || frontmatter.cover || frontmatter.ogImage || '', tags: frontmatter.tags || [], order: typeof frontmatter.order === 'number' ? frontmatter.order : 9999, featured: frontmatter.featured === true, contentDir: page.contentDir, product, type, status, category, subcategory, price: product.price ?? null, currency: String(product.currency || 'KRW'), releaseDate: String(product.releaseDate || frontmatter.releaseDate || frontmatter.date || ''), series, collection }
  }).sort((a, b) => a.order - b.order || a.title.localeCompare(b.title))
}
function normalizeText(value: string): string { return value.trim().toLocaleLowerCase() }
function entrySearchText(entry: ProductCatalogEntry): string { return [entry.title, entry.description, entry.tags.join(' '), entry.type, entry.status, entry.category, entry.subcategory, entry.series, entry.collection, entry.product.sku || '', entry.product.material || '', entry.product.size || '', entry.product.license || ''].join(' ').toLocaleLowerCase() }
export function filterProductCatalogEntries(entries: ProductCatalogEntry[], filter: ProductCatalogFilter = {}): ProductCatalogEntry[] {
  const query = normalizeText(filter.query || ''); const status = normalizeTaxonomyValue(filter.status || 'all') || 'all'; const type = normalizeTaxonomyValue(filter.type || 'all') || 'all'; const category = normalizeTaxonomyValue(filter.category || 'all') || 'all'; const subcategory = normalizeTaxonomyValue(filter.subcategory || 'all') || 'all'; const collection = normalizeTaxonomyValue(filter.collection || 'all') || 'all'; const tag = String(filter.tag || 'all'); const showUnavailable = filter.showUnavailable !== false
  return entries.filter((entry) => { if (!showUnavailable && (entry.status === 'coming-soon' || entry.status === 'sold-out')) return false; if (status !== 'all' && entry.status !== status) return false; if (type !== 'all' && entry.type !== type) return false; if (category !== 'all' && entry.category !== category) return false; if (subcategory !== 'all' && entry.subcategory !== subcategory) return false; if (collection !== 'all' && entry.collection !== collection) return false; if (tag !== 'all' && !entry.tags.includes(tag)) return false; if (query && !entrySearchText(entry).includes(query)) return false; return true })
}
export function sortProductCatalogEntries(entries: ProductCatalogEntry[], sort: ProductCatalogSort = 'order'): ProductCatalogEntry[] { const list = [...entries]; switch (sort) { case 'title': return list.sort((a, b) => a.title.localeCompare(b.title)); case 'newest': return list.sort((a, b) => (b.releaseDate || '').localeCompare(a.releaseDate || '') || a.order - b.order); case 'oldest': return list.sort((a, b) => (a.releaseDate || '').localeCompare(b.releaseDate || '') || a.order - b.order); case 'price-low': return list.sort((a, b) => { const pa = normalizeProductPrice(a.price); const pb = normalizeProductPrice(b.price); if (pa === null && pb === null) return a.order - b.order; if (pa === null) return 1; if (pb === null) return -1; return pa - pb || a.order - b.order }); case 'price-high': return list.sort((a, b) => { const pa = normalizeProductPrice(a.price); const pb = normalizeProductPrice(b.price); if (pa === null && pb === null) return a.order - b.order; if (pa === null) return 1; if (pb === null) return -1; return pb - pa || a.order - b.order }); case 'order': default: return list.sort((a, b) => a.order - b.order || a.title.localeCompare(b.title)) } }
function uniqueSorted(values: string[]): string[] { return Array.from(new Set(values.map((v) => v.trim()).filter(Boolean))).sort((a, b) => a.localeCompare(b)) }
export function getAvailableProductStatuses(entries: ProductCatalogEntry[]): string[] { const preferred = ['available', 'coming-soon', 'sold-out']; const present = new Set(entries.map((e) => e.status).filter(Boolean)); return preferred.filter((s) => present.has(s)) }
export function getAvailableProductTypes(entries: ProductCatalogEntry[]): string[] { return sortByTaxonomyOrder('type', entries.map((e) => e.type)) }
export function getAvailableProductCategories(entries: ProductCatalogEntry[]): string[] { return sortByTaxonomyOrder('category', entries.map((e) => e.category)) }
export function getAvailableProductSubcategories(entries: ProductCatalogEntry[]): string[] { return sortByTaxonomyOrder('subcategory', entries.map((e) => e.subcategory)) }
export function getAvailableProductCollections(entries: ProductCatalogEntry[]): string[] { return sortByTaxonomyOrder('collection', entries.map((e) => e.collection)) }
export function getAvailableProductTags(entries: ProductCatalogEntry[]): string[] { return uniqueSorted(entries.flatMap((e) => e.tags)) }


export type ProductFacetCount = { id: string; label: string; href: string; count: number; visible: boolean; disabled: boolean; current: boolean; description?: string; order: number }
function cleanHrefBase(value: string | undefined, fallback: string): string { const raw = String(value || fallback).trim() || fallback; return raw.replace(/\/+$/, '') || fallback }
function countBy(entries: ProductCatalogEntry[], key: 'category' | 'collection'): Map<string, number> { const counts = new Map<string, number>(); for (const entry of entries) { const id = normalizeTaxonomyValue(entry[key]); if (!id) continue; counts.set(id, (counts.get(id) || 0) + 1) } return counts }
export function getProductCategoryFacetCounts(pages: LoadedMarkdownPage[], options: { currentCategory?: string; showEmpty?: boolean; hrefBase?: string } = {}): ProductFacetCount[] { const entries = getProductCatalogEntries(pages); const counts = countBy(entries, 'category'); const currentCategory = normalizeTaxonomyValue(options.currentCategory || ''); const hrefBase = cleanHrefBase(options.hrefBase, '/products/categories'); return getProductCategoryOptions(false).map((item) => { const count = counts.get(item.id) || 0; const disabled = count === 0; return { id: item.id, label: resolveProductCategoryLabel(item.id), href: `${hrefBase}/${item.id}`, count, visible: !disabled || options.showEmpty === true, disabled, current: currentCategory === item.id, description: item.description, order: item.order } }).filter((item) => item.visible) }
export function getProductCollectionFacetCounts(pages: LoadedMarkdownPage[], options: { currentCollection?: string; showEmpty?: boolean; hrefBase?: string } = {}): ProductFacetCount[] { const entries = getProductCatalogEntries(pages); const counts = countBy(entries, 'collection'); const currentCollection = normalizeTaxonomyValue(options.currentCollection || ''); const hrefBase = cleanHrefBase(options.hrefBase, '/products/collections'); return getProductCollectionOptions(false).map((item) => { const count = counts.get(item.id) || 0; const disabled = count === 0; return { id: item.id, label: resolveProductCollectionLabel(item.id), href: `${hrefBase}/${item.id}`, count, visible: !disabled || options.showEmpty === true, disabled, current: currentCollection === item.id, description: item.description, order: item.order } }).filter((item) => item.visible) }
