<script setup lang="ts">
import { onMounted, ref } from 'vue'
import InquiryDetailPanel from '@/components/inquiries/InquiryDetailPanel.vue'
import InquiryFilterBar from '@/components/inquiries/InquiryFilterBar.vue'
import InquiryQueueTable from '@/components/inquiries/InquiryQueueTable.vue'
import { addAdminInquiryNote, fetchAdminInquiries, fetchAdminInquiryDetail, updateAdminInquiryPriority, updateAdminInquiryStatus } from '@/lib/adminInquiryApi'
import type { AdminInquiryDetail, AdminInquiryListItem, AdminInquiryListQuery, InquiryPriority, InquiryStatus } from '@/types/inquiryAdmin'
const filters=ref<AdminInquiryListQuery>({ status:'all', priority:'all', limit:50, offset:0 }); const items=ref<AdminInquiryListItem[]>([]); const selectedId=ref(''); const detail=ref<AdminInquiryDetail|null>(null); const loadingList=ref(false); const loadingDetail=ref(false); const error=ref(''); const notice=ref('')
async function loadList(){ loadingList.value=true; error.value=''; try{ const result=await fetchAdminInquiries(filters.value); items.value=result.items; if(!selectedId.value && result.items[0]) await selectInquiry(result.items[0]) }catch(caught){ error.value=caught instanceof Error?caught.message:'Admin inquiry queue request failed.' }finally{ loadingList.value=false } }
async function selectInquiry(item:AdminInquiryListItem){ selectedId.value=item.id; loadingDetail.value=true; error.value=''; try{ detail.value=await fetchAdminInquiryDetail(item.id) }catch(caught){ error.value=caught instanceof Error?caught.message:'Admin inquiry detail request failed.' }finally{ loadingDetail.value=false } }
async function refreshSelected(){ if(!selectedId.value) return; detail.value=await fetchAdminInquiryDetail(selectedId.value); const result=await fetchAdminInquiries(filters.value); items.value=result.items }
async function onUpdateStatus(status:InquiryStatus,note:string){ if(!selectedId.value) return; await updateAdminInquiryStatus(selectedId.value,{ status,note:note||undefined }); notice.value=`Status updated to ${status}.`; await refreshSelected() }
async function onUpdatePriority(priority:InquiryPriority,note:string){ if(!selectedId.value) return; await updateAdminInquiryPriority(selectedId.value,{ priority,note:note||undefined }); notice.value=`Priority updated to ${priority}.`; await refreshSelected() }
async function onAddNote(note:string){ if(!selectedId.value) return; if(!note.trim()){ error.value='Admin note is required.'; return } await addAdminInquiryNote(selectedId.value,{ note }); notice.value='Admin note event added.'; await refreshSelected() }
onMounted(loadList)
</script>
<template><section class="panel"><p class="eyebrow">Commit 118</p><h2>Inquiry Review Queue</h2><p class="intro">Private admin queue for D1-backed inquiry intake. This is not a public board, not a customer lookup surface, and not a notification workflow.</p><InquiryFilterBar v-model="filters" @apply="loadList" /><p v-if="loadingList">Loading inquiries from Admin API Worker...</p><p v-if="error" role="alert" class="error">{{ error }}</p><p v-if="notice" role="status" class="notice">{{ notice }}</p><div class="queue-layout"><InquiryQueueTable :items="items" :selected-id="selectedId" @select="selectInquiry" /><InquiryDetailPanel :inquiry="detail" :loading="loadingDetail" @update-status="onUpdateStatus" @update-priority="onUpdatePriority" @add-note="onAddNote" /></div></section></template>
<style scoped>.panel{display:grid;gap:16px;max-width:1500px;padding:28px;border:1px solid rgba(36,31,26,.12);border-radius:24px;background:rgba(255,255,255,.66)}.eyebrow{margin:0;font-size:12px;font-weight:800;letter-spacing:.12em;text-transform:uppercase;color:#8b5d2e}h2{margin:0;font-size:clamp(30px,4vw,48px);line-height:1.04}.intro{max-width:820px;line-height:1.7;color:rgba(36,31,26,.76)}.queue-layout{display:grid;grid-template-columns:minmax(0,1.25fr) minmax(360px,.75fr);gap:18px;align-items:start}.error,.notice{padding:12px 14px;border-radius:14px}.error{background:rgba(122,59,42,.12);color:#7a3b2a}.notice{background:rgba(139,93,46,.12);color:#5f3b18}@media(max-width:1180px){.queue-layout{grid-template-columns:1fr}}</style>
