import { assertManifest,type SegmentStreamManifest } from './segmentedPlaybackManifest'

function ownedArrayBuffer(
  bytes: Uint8Array<ArrayBufferLike> | ArrayBuffer,
): ArrayBuffer {
  if (bytes instanceof ArrayBuffer) {
    return bytes
  }

  const copy = new Uint8Array(bytes.byteLength)
  copy.set(bytes)
  return copy.buffer
}

export type SchedulerReceipt={revision:'SEGMENT_SCHEDULER_DATA_BUDGET_V1';explicitPlayCount:number;manifestRequestCount:number;manifestBytes:number;videoInitBytes:number;audioInitBytes:number;segmentIntervalRequests:number;videoSegmentBytes:number;audioSegmentBytes:number;totalMediaBytesReceived:number;peakForwardBufferUs:number;maxConcurrentIntervalRequests:number;pauseAbortCount:number;outOfViewAbortCount:number;seekAbortCount:number;requestsStartedWhilePaused:number;requestsStartedWhileOutOfView:number;progressiveMp4RequestCount:0;dataBudgetPass:boolean}
function absolute(base:string,path:string){return new URL(path,base).toString()}
function waitUpdate(sb:SourceBuffer){return new Promise<void>((resolve,reject)=>{if(!sb.updating)return resolve();const done=()=>{cleanup();resolve()},bad=()=>{cleanup();reject(new Error('E_PUBLIC_SOURCEBUFFER_UPDATE'))},cleanup=()=>{sb.removeEventListener('updateend',done);sb.removeEventListener('error',bad)};sb.addEventListener('updateend',done,{once:true});sb.addEventListener('error',bad,{once:true})})}
export class SegmentedPlaybackSession{
  private manifest:SegmentStreamManifest|null=null;private mediaSource:MediaSource|null=null;private videoBuffer:SourceBuffer|null=null;private audioBuffer:SourceBuffer|null=null;private generation=0;private aborter:AbortController|null=null;private loaded=new Set<number>();private inflight=new Set<number>();private started=false
  readonly receipt:SchedulerReceipt={revision:'SEGMENT_SCHEDULER_DATA_BUDGET_V1',explicitPlayCount:0,manifestRequestCount:0,manifestBytes:0,videoInitBytes:0,audioInitBytes:0,segmentIntervalRequests:0,videoSegmentBytes:0,audioSegmentBytes:0,totalMediaBytesReceived:0,peakForwardBufferUs:0,maxConcurrentIntervalRequests:0,pauseAbortCount:0,outOfViewAbortCount:0,seekAbortCount:0,requestsStartedWhilePaused:0,requestsStartedWhileOutOfView:0,progressiveMp4RequestCount:0,dataBudgetPass:true}
  constructor(private video:HTMLVideoElement,private manifestUrl:string){}
  private async fetchBytes(url:string,signal:AbortSignal){const r=await fetch(url,{signal,credentials:'omit',cache:'default'});if(!r.ok)throw new Error(`E_PUBLIC_SEGMENT_FETCH_${r.status}`);return new Uint8Array(await r.arrayBuffer())}
  private async ensureManifest(signal:AbortSignal){if(this.manifest)return this.manifest;this.receipt.manifestRequestCount++;const r=await fetch(this.manifestUrl,{signal,credentials:'omit',cache:'default'});if(!r.ok)throw new Error(`E_PUBLIC_SEGMENT_MANIFEST_${r.status}`);const text=await r.text();this.receipt.manifestBytes+=new TextEncoder().encode(text).byteLength;this.manifest=assertManifest(JSON.parse(text));return this.manifest}
  private async openMediaSource(m:SegmentStreamManifest,signal:AbortSignal){if(this.mediaSource)return;const ms=new MediaSource();this.mediaSource=ms;this.video.src=URL.createObjectURL(ms);await new Promise<void>((resolve,reject)=>{ms.addEventListener('sourceopen',()=>resolve(),{once:true});ms.addEventListener('error',()=>reject(new Error('E_PUBLIC_MEDIA_SOURCE_OPEN')),{once:true})});this.videoBuffer=ms.addSourceBuffer(`video/mp4; codecs=\"${m.video.codec}\"`);if(m.audio)this.audioBuffer=ms.addSourceBuffer(`audio/mp4; codecs=\"${m.audio.codec}\"`);const vi=await this.fetchBytes(absolute(this.manifestUrl,m.video.init.path),signal);this.receipt.videoInitBytes+=vi.byteLength;this.videoBuffer.appendBuffer(ownedArrayBuffer(vi));await waitUpdate(this.videoBuffer);if(m.audio&&this.audioBuffer){const ai=await this.fetchBytes(absolute(this.manifestUrl,m.audio.init.path),signal);this.receipt.audioInitBytes+=ai.byteLength;this.audioBuffer.appendBuffer(ownedArrayBuffer(ai));await waitUpdate(this.audioBuffer)}}
  private indexFor(time:number,m:SegmentStreamManifest){const us=Math.max(0,time*1e6);let idx=0;for(let i=0;i<m.segments.length;i++){const s=m.segments[i];if(us>=s.startUs)idx=i;else break}return idx}
  private async appendInterval(index:number,generation:number,signal:AbortSignal){const m=this.manifest!;if(index<0||index>=m.segments.length||this.loaded.has(index)||this.inflight.has(index)||generation!==this.generation)return;this.inflight.add(index);this.receipt.maxConcurrentIntervalRequests=Math.max(this.receipt.maxConcurrentIntervalRequests,this.inflight.size);if(this.inflight.size>1)throw new Error('E_PUBLIC_SEGMENT_INFLIGHT_BUDGET');try{const s=m.segments[index];this.receipt.segmentIntervalRequests++;const vb=await this.fetchBytes(absolute(this.manifestUrl,s.video.path),signal);if(generation!==this.generation)return;this.receipt.videoSegmentBytes+=vb.byteLength;this.receipt.totalMediaBytesReceived+=vb.byteLength;let ab:Uint8Array|null=null;if(s.audio){ab=await this.fetchBytes(absolute(this.manifestUrl,s.audio.path),signal);if(generation!==this.generation)return;this.receipt.audioSegmentBytes+=ab.byteLength;this.receipt.totalMediaBytesReceived+=ab.byteLength}if(!this.videoBuffer)throw new Error('E_PUBLIC_SEGMENT_VIDEO_BUFFER_MISSING');await waitUpdate(this.videoBuffer);this.videoBuffer.appendBuffer(ownedArrayBuffer(vb));await waitUpdate(this.videoBuffer);if(ab&&this.audioBuffer){await waitUpdate(this.audioBuffer);this.audioBuffer.appendBuffer(ownedArrayBuffer(ab));await waitUpdate(this.audioBuffer)}this.loaded.add(index)}finally{this.inflight.delete(index)}}
  async explicitPlay(){this.receipt.explicitPlayCount++;this.started=true;this.generation++;this.aborter?.abort();this.aborter=new AbortController();const g=this.generation,m=await this.ensureManifest(this.aborter.signal);await this.openMediaSource(m,this.aborter.signal);const i=this.indexFor(this.video.currentTime,m);await this.appendInterval(i,g,this.aborter.signal);void this.appendInterval(i+1,g,this.aborter.signal);await this.video.play()}
  pause(){this.video.pause();this.generation++;this.aborter?.abort();this.receipt.pauseAbortCount++}
  outOfView(){this.pause();this.receipt.outOfViewAbortCount++}
  async seek(time:number){if(!this.started){this.video.currentTime=time;return}this.generation++;this.aborter?.abort();this.receipt.seekAbortCount++;this.aborter=new AbortController();const m=await this.ensureManifest(this.aborter.signal);this.video.currentTime=time;const i=this.indexFor(time,m);const g=this.generation;await this.appendInterval(i,g,this.aborter.signal);void this.appendInterval(i+1,g,this.aborter.signal)}
  async pump(){if(!this.started||this.video.paused||!this.manifest||!this.aborter)return;const i=this.indexFor(this.video.currentTime,this.manifest);const end=(this.manifest.segments[Math.min(this.manifest.segments.length-1,i+1)]?.startUs??0)+(this.manifest.segments[Math.min(this.manifest.segments.length-1,i+1)]?.durationUs??0);this.receipt.peakForwardBufferUs=Math.max(this.receipt.peakForwardBufferUs,Math.max(0,end-this.video.currentTime*1e6));await this.appendInterval(i+1,this.generation,this.aborter.signal)}
  destroy(){this.generation++;this.aborter?.abort();this.video.pause();this.video.removeAttribute('src');this.video.load();this.mediaSource=null;this.videoBuffer=null;this.audioBuffer=null}
}
