import type { NavigationItem } from './navigationTypes'

export const pageIndex = [
  {
    id: 'home',
    label: '홈',
    href: '/',
    section: 'home',
    surface: ['hidden'],
    order: 0,
    description: '바룬툴즈 홈.',
  },
  {
    id: 'works',
    label: '작업',
    href: '/works',
    section: 'works',
    surface: ['header', 'footer', 'section'],
    order: 10,
    description: '대표 포트폴리오 작업과 케이스 스터디.',
  },
  {
    id: 'works-varuntools-showroom',
    label: 'VarunTools Showroom',
    href: '/works/varuntools-showroom',
    section: 'works',
    surface: ['section', 'footer'],
    order: 11,
    description: '현재 포트폴리오 시스템의 쇼룸 케이스.',
    featured: true,
  },
  {
    id: 'products',
    label: '상품',
    href: '/products',
    section: 'products',
    surface: ['header', 'footer', 'section'],
    order: 20,
    description: '스토어와 디지털 상품 입구.',
  },
  {
    id: 'products-categories',
    label: '분류',
    href: '/products/categories',
    section: 'products',
    surface: ['section', 'footer'],
    order: 21,
    description: '상품 분류 인덱스.',
  },
  {
    id: 'products-category-templates',
    label: '템플릿',
    href: '/products/categories/templates',
    section: 'products',
    surface: ['section'],
    order: 22,
    description: '템플릿 상품 분류.',
  },
  {
    id: 'tools-wiper',
    label: '전후 비교',
    href: '/wiper',
    section: 'tools',
    surface: ['header', 'footer', 'section'],
    order: 30,
    description: '이미지 전후 비교 도구 페이지.',
    featured: true,
  },
  {
    id: 'lab-markdown-gallery',
    label: '마크다운 갤러리',
    href: '/lab-markdown-gallery',
    section: 'lab',
    surface: ['footer', 'section'],
    order: 40,
    description: '마크다운 렌더링 예시를 모은 공개 실험실 갤러리.',
    featured: true,
  },
  {
    id: 'inquiry',
    label: '문의',
    href: '/inquiry',
    section: 'inquiry',
    surface: ['header', 'footer', 'utility'],
    order: 90,
    description: '문의 접수 폼.',
  },
] as const satisfies readonly NavigationItem[]
