import type { NavigationItem } from './navigationTypes'

export const pageIndex = [
  {
    id: 'home',
    label: 'Home',
    href: '/',
    section: 'home',
    surface: ['header', 'footer'],
    order: 0,
    description: 'Varun Tools home.',
  },
  {
    id: 'works',
    label: 'Works',
    href: '/works',
    section: 'works',
    surface: ['header', 'footer', 'section'],
    order: 10,
    description: 'Featured portfolio work and editorial case studies.',
  },
  {
    id: 'works-varuntools-showroom',
    label: 'VarunTools Showroom',
    href: '/works/varuntools-showroom',
    section: 'works',
    surface: ['section', 'footer'],
    order: 11,
    description: 'Showroom case for the current portfolio system.',
    featured: true,
  },
  {
    id: 'products',
    label: 'Products',
    href: '/products',
    section: 'products',
    surface: ['header', 'footer', 'section'],
    order: 20,
    description: 'Store and digital product entry.',
  },
  {
    id: 'products-categories',
    label: 'Categories',
    href: '/products/categories',
    section: 'products',
    surface: ['section', 'footer'],
    order: 21,
    description: 'Product category index.',
  },
  {
    id: 'products-category-templates',
    label: 'Templates',
    href: '/products/categories/templates',
    section: 'products',
    surface: ['section'],
    order: 22,
    description: 'Template product category.',
  },
  {
    id: 'tools-wiper',
    label: 'Wiper',
    href: '/wiper',
    section: 'tools',
    surface: ['header', 'footer', 'section'],
    order: 30,
    description: 'Before/after image comparison tool page.',
    featured: true,
  },
  {
    id: 'lab-markdown-gallery',
    label: 'Markdown Gallery',
    href: '/lab-markdown-gallery',
    section: 'lab',
    surface: ['footer', 'section'],
    order: 40,
    description: 'Public lab gallery for markdown rendering examples.',
    featured: true,
  },
  {
    id: 'inquiry',
    label: 'Inquiry',
    href: '/inquiry',
    section: 'inquiry',
    surface: ['header', 'footer', 'utility'],
    order: 90,
    description: 'Private inquiry intake form.',
  },
] as const satisfies readonly NavigationItem[]
