import type { AccessIdentity, AdminAuditLogQuery, AdminDryRunInput, AdminListQuery, AdminWriteActionPlan, Env } from './types'
import type { AddInquiryNoteRequest, AdminInquiryListQuery, UpdateInquiryPriorityRequest, UpdateInquiryStatusRequest } from './inquiryTypes'
import { adminApiMode, adminDbConfigured, inquiryDbConfigured } from './env'
import { fail, methodNotAllowed, ok, parseLimit, parseOffset } from './http'
import { verifyAccessRequest } from './access'
import { listAdminActionAuditLog, listGrants, listOrders, listWebhookEvents } from './db'
import { listDeliveryIncidents, listProductOps } from './readModels'
import { AdminAuditLogWriteError, makeAdminRequestId, recordAdminDryRunAudit } from './auditLog'
import { planGrantReissue, planGrantRevoke, planRefundNote, planSupportNote, planWebhookReplay } from './writeActionPlans'
import { addAdminInquiryNote, listAdminInquiries, readAdminInquiryDetail, updateAdminInquiryPriority, updateAdminInquiryStatus } from './inquiries'
async function readDryRunBody(request:Request):Promise<AdminDryRunInput>{ try{return await request.json() as AdminDryRunInput}catch{return {}} }
async function readJsonBody<T>(request:Request):Promise<T>{ try{return await request.json() as T}catch{return {} as T} }
async function respondWithAuditedDryRun(request:Request,env:Env,identity:AccessIdentity,input:AdminDryRunInput,plan:AdminWriteActionPlan):Promise<Response>{ const requestId=makeAdminRequestId(); const now=new Date().toISOString(); try{ const auditedPlan=await recordAdminDryRunAudit(env,{identity,plan,dryRunInput:input,request,requestId,now}); return ok(auditedPlan,{requestId}) }catch(error){ if(error instanceof AdminAuditLogWriteError) return fail(error.status,error.code,error.message); const message=error instanceof Error?error.message:'Admin write dry-run audit log could not be recorded.'; return fail(500,'ADMIN_AUDIT_LOG_WRITE_FAILED',message) } }
async function handleDryRun(request:Request,env:Env,identity:AccessIdentity,url:URL):Promise<Response|null>{ if(!url.pathname.includes('/api/write-actions/')) return null; if(request.method!=='POST') return methodNotAllowed('Use POST for dry-run write action planning endpoints.'); const input=await readDryRunBody(request); const grantRevoke=url.pathname.match(/\/api\/write-actions\/grants\/([^/]+)\/revoke\/dry-run$/); if(grantRevoke) return respondWithAuditedDryRun(request,env,identity,input,await planGrantRevoke(env,identity,decodeURIComponent(grantRevoke[1]),input)); const grantReissue=url.pathname.match(/\/api\/write-actions\/grants\/([^/]+)\/reissue\/dry-run$/); if(grantReissue) return respondWithAuditedDryRun(request,env,identity,input,await planGrantReissue(env,identity,decodeURIComponent(grantReissue[1]),input)); const refundNote=url.pathname.match(/\/api\/write-actions\/orders\/([^/]+)\/refund-note\/dry-run$/); if(refundNote) return respondWithAuditedDryRun(request,env,identity,input,await planRefundNote(env,identity,decodeURIComponent(refundNote[1]),input)); const supportNote=url.pathname.match(/\/api\/write-actions\/orders\/([^/]+)\/support-note\/dry-run$/); if(supportNote) return respondWithAuditedDryRun(request,env,identity,input,await planSupportNote(env,identity,decodeURIComponent(supportNote[1]),input)); const webhookReplay=url.pathname.match(/\/api\/write-actions\/webhook-events\/([^/]+)\/replay\/dry-run$/); if(webhookReplay) return respondWithAuditedDryRun(request,env,identity,input,await planWebhookReplay(env,identity,decodeURIComponent(webhookReplay[1]),input)); return fail(404,'NOT_FOUND','Unknown dry-run write action planning route.') }
function makeAuditLogQuery(url:URL):AdminAuditLogQuery{ return { limit:parseLimit(url), offset:parseOffset(url), actionKind:(url.searchParams.get('actionKind')??undefined) as AdminAuditLogQuery['actionKind'], targetId:url.searchParams.get('targetId')??undefined, requestId:url.searchParams.get('requestId')??undefined } }
function makeAdminListQuery(url:URL):AdminListQuery{ return { limit:parseLimit(url), offset:parseOffset(url), status:url.searchParams.get('status')??undefined, productSlug:url.searchParams.get('productSlug')??undefined, orderId:url.searchParams.get('orderId')??undefined } }
function makeInquiryListQuery(url:URL):AdminInquiryListQuery{ return { limit:parseLimit(url), offset:parseOffset(url), status:(url.searchParams.get('status')??undefined) as AdminInquiryListQuery['status'], priority:(url.searchParams.get('priority')??undefined) as AdminInquiryListQuery['priority'], category:url.searchParams.get('category')??undefined, search:url.searchParams.get('search')??undefined } }
async function handleInquiryAdminRoute(request:Request,env:Env,identity:AccessIdentity,url:URL):Promise<Response|null>{ if(!url.pathname.startsWith('/api/inquiries')) return null; if(!inquiryDbConfigured(env)) return fail(501,'INQUIRY_DB_NOT_CONFIGURED','INQUIRY_DB D1 binding is required for admin inquiry review queue.'); if(url.pathname==='/api/inquiries'){ if(request.method!=='GET') return methodNotAllowed('Use GET for admin inquiry list endpoint.'); return ok(await listAdminInquiries(env,makeInquiryListQuery(url))) } const statusMatch=url.pathname.match(/^\/api\/inquiries\/([^/]+)\/status$/); if(statusMatch){ if(request.method!=='PATCH') return methodNotAllowed('Use PATCH for inquiry status updates.'); const result=await updateAdminInquiryStatus(env,identity,decodeURIComponent(statusMatch[1]),await readJsonBody<UpdateInquiryStatusRequest>(request)); return result.ok?ok(result.data):fail(result.status,result.code,result.message) } const priorityMatch=url.pathname.match(/^\/api\/inquiries\/([^/]+)\/priority$/); if(priorityMatch){ if(request.method!=='PATCH') return methodNotAllowed('Use PATCH for inquiry priority updates.'); const result=await updateAdminInquiryPriority(env,identity,decodeURIComponent(priorityMatch[1]),await readJsonBody<UpdateInquiryPriorityRequest>(request)); return result.ok?ok(result.data):fail(result.status,result.code,result.message) } const eventsMatch=url.pathname.match(/^\/api\/inquiries\/([^/]+)\/events$/); if(eventsMatch){ if(request.method!=='POST') return methodNotAllowed('Use POST for inquiry admin note events.'); const result=await addAdminInquiryNote(env,identity,decodeURIComponent(eventsMatch[1]),await readJsonBody<AddInquiryNoteRequest>(request)); return result.ok?ok(result.data):fail(result.status,result.code,result.message) } const detailMatch=url.pathname.match(/^\/api\/inquiries\/([^/]+)$/); if(detailMatch){ if(request.method!=='GET') return methodNotAllowed('Use GET for admin inquiry detail endpoint.'); const detail=await readAdminInquiryDetail(env,decodeURIComponent(detailMatch[1])); return detail?ok(detail):fail(404,'NOT_FOUND','Inquiry was not found.') } return fail(404,'NOT_FOUND','Unknown admin inquiry review queue route.') }
export default { async fetch(request:Request,env:Env):Promise<Response>{ const access=await verifyAccessRequest(request,env); if(!access.ok) return fail(access.status,access.code,access.message); if(adminApiMode(env)==='not_configured') return fail(501,'ADMIN_API_NOT_CONFIGURED','Admin API mode is not configured.'); const url=new URL(request.url); const dryRun=await handleDryRun(request,env,access.identity,url); if(dryRun) return dryRun; const inquiryRoute=await handleInquiryAdminRoute(request,env,access.identity,url); if(inquiryRoute) return inquiryRoute; if(request.method!=='GET') return methodNotAllowed(); if(url.pathname.endsWith('/api/health')) return ok({ service:'varuntools-admin-api', mode:'read-mostly-with-audit-ledger', d1:adminDbConfigured(env)?'configured':'missing', inquiryD1:inquiryDbConfigured(env)?'configured':'missing', access:'verified', writeMode:env.ADMIN_WRITE_MODE??'disabled' }); if(url.pathname.endsWith('/api/session')) return ok({ user:{ email:access.identity.email, aud:access.identity.aud, expiresAt:new Date(access.identity.exp*1000).toISOString() } }); if(!adminDbConfigured(env)) return fail(501,'ADMIN_DB_NOT_CONFIGURED','ADMIN_DB D1 binding is required for this Admin API route.'); const query=makeAdminListQuery(url); if(url.pathname.endsWith('/api/orders')) return ok(await listOrders(env,query)); if(url.pathname.endsWith('/api/grants')) return ok(await listGrants(env,query)); if(url.pathname.endsWith('/api/webhook-events')) return ok(await listWebhookEvents(env,query)); if(url.pathname.endsWith('/api/audit-log')) return ok(await listAdminActionAuditLog(env,makeAuditLogQuery(url))); if(url.pathname.endsWith('/api/products')) return ok(await listProductOps(env)); if(url.pathname.endsWith('/api/delivery-incidents')) return ok(await listDeliveryIncidents(env)); return fail(404,'NOT_FOUND','Unknown read-only Admin API route.') } }
