import type { AccessIdentity, Env, Paginated } from './types'
import { INQUIRY_PRIORITIES, INQUIRY_STATUSES, type AddInquiryNoteRequest, type AddInquiryNoteResponse, type AdminInquiryDetail, type AdminInquiryEvent, type AdminInquiryListItem, type AdminInquiryListQuery, type InquiryEventType, type InquiryPriority, type InquiryStatus, type UpdateInquiryPriorityRequest, type UpdateInquiryPriorityResponse, type UpdateInquiryStatusRequest, type UpdateInquiryStatusResponse } from './inquiryTypes'
import { canTransitionInquiryStatus, describeInvalidInquiryTransition, transitionRequiresNote } from './inquiryStatusTransition'

type InquiryDb = D1Database
type Row = Record<string, unknown>
type MutationResult = | { ok:true; data:UpdateInquiryStatusResponse|UpdateInquiryPriorityResponse|AddInquiryNoteResponse } | { ok:false; status:number; code:string; message:string; fieldErrors?:Record<string,string> }
function db(env:Env):InquiryDb{ const out=env.INQUIRY_DB ?? env.ADMIN_DB; if(!out) throw new Error('INQUIRY_DB binding is required for admin inquiry review queue.'); return out }
function page<T>(items:T[], limit:number, offset:number):Paginated<T>{ return { items, limit, offset, nextCursor: items.length===limit ? String(offset+limit) : null } }
function text(v:unknown):string{ return String(v??'') }
function opt(v:unknown):string|undefined{ const s=String(v??'').trim(); return s || undefined }
function nul(v:unknown):string|null{ return opt(v) ?? null }
function isStatus(v:string):v is InquiryStatus{ return INQUIRY_STATUSES.includes(v as InquiryStatus) }
function isPriority(v:string):v is InquiryPriority{ return INQUIRY_PRIORITIES.includes(v as InquiryPriority) }
function actor(identity:AccessIdentity):string{ return identity.email || identity.sub || 'admin' }
function eventId():string{ const now=new Date().toISOString().replace(/[-:.TZ]/g,''); const random=Math.random().toString(36).slice(2,10); return `inqevt_admin_${now}_${random}` }
function toListItem(r:Row):AdminInquiryListItem{ const status=text(r.status); const priority=text(r.priority); return { id:text(r.id), createdAt:text(r.created_at), updatedAt:text(r.updated_at), receivedAt:text(r.received_at), status:isStatus(status)?status:'new', priority:isPriority(priority)?priority:'normal', category:text(r.category), nickname:opt(r.nickname), email:opt(r.email), title:text(r.title), relatedProductSlug:opt(r.related_product_slug), sourcePath:opt(r.source_path) } }
function toEvent(r:Row):AdminInquiryEvent{ return { id:text(r.id), inquiryId:text(r.inquiry_id), createdAt:text(r.created_at), eventType:text(r.event_type) as InquiryEventType, note:opt(r.note), actor:opt(r.actor), metadataJson:opt(r.metadata_json) } }
function toDetail(r:Row, events:AdminInquiryEvent[]):AdminInquiryDetail{ return { ...toListItem(r), message:text(r.message), sourceUrl:opt(r.source_url), clientFingerprint:opt(r.client_fingerprint), userAgent:opt(r.user_agent), payloadJson:text(r.payload_json), events } }
function where(q:AdminInquiryListQuery):{ where:string; binds:unknown[] }{ const clauses:string[]=[]; const binds:unknown[]=[]; if(q.status&&q.status!=='all'){ clauses.push('status = ?'); binds.push(q.status) } if(q.priority&&q.priority!=='all'){ clauses.push('priority = ?'); binds.push(q.priority) } if(q.category){ clauses.push('category = ?'); binds.push(q.category) } if(q.search){ const like=`%${q.search}%`; clauses.push('(title LIKE ? OR message LIKE ? OR nickname LIKE ? OR email LIKE ? OR related_product_slug LIKE ?)'); binds.push(like,like,like,like,like) } return { where:clauses.length?`WHERE ${clauses.join(' AND ')}`:'', binds } }
async function rowById(database:InquiryDb,id:string):Promise<Row|null>{ return database.prepare(`SELECT id, created_at, updated_at, received_at, status, priority, category, nickname, email, title, message, related_product_slug, source_path, source_url, client_fingerprint, user_agent, payload_json FROM inquiries WHERE id = ? LIMIT 1`).bind(id).first<Row>() }
async function createEvent(database:InquiryDb,input:{ inquiryId:string; eventType:InquiryEventType; note?:string; actor?:string; metadata?:Record<string,unknown>; createdAt:string }):Promise<string>{ const id=eventId(); await database.prepare(`INSERT INTO inquiry_events (id, inquiry_id, created_at, event_type, note, actor, metadata_json) VALUES (?, ?, ?, ?, ?, ?, ?)`).bind(id,input.inquiryId,input.createdAt,input.eventType,nul(input.note),nul(input.actor),input.metadata?JSON.stringify(input.metadata):null).run(); return id }
export async function listAdminInquiries(env:Env,q:AdminInquiryListQuery):Promise<Paginated<AdminInquiryListItem>>{ const database=db(env); const built=where(q); const result=await database.prepare(`SELECT id, created_at, updated_at, received_at, status, priority, category, nickname, email, title, related_product_slug, source_path FROM inquiries ${built.where} ORDER BY created_at DESC LIMIT ? OFFSET ?`).bind(...built.binds,q.limit,q.offset).all<Row>(); return page((result.results??[]).map(toListItem),q.limit,q.offset) }
export async function readAdminInquiryDetail(env:Env,id:string):Promise<AdminInquiryDetail|null>{ const database=db(env); const row=await rowById(database,id); if(!row) return null; const result=await database.prepare('SELECT id, inquiry_id, created_at, event_type, note, actor, metadata_json FROM inquiry_events WHERE inquiry_id = ? ORDER BY created_at ASC').bind(id).all<Row>(); return toDetail(row,(result.results??[]).map(toEvent)) }
export async function updateAdminInquiryStatus(env:Env,identity:AccessIdentity,id:string,input:UpdateInquiryStatusRequest):Promise<MutationResult>{ if(!isStatus(input.status)) return { ok:false,status:400,code:'VALIDATION_FAILED',message:'Invalid inquiry status.',fieldErrors:{status:'Invalid inquiry status.'} }; const database=db(env); const current=await rowById(database,id); if(!current) return { ok:false,status:404,code:'NOT_FOUND',message:'Inquiry was not found.' }; const previousStatus=toListItem(current).status; const nextStatus=input.status; const note=input.note?.trim()||''; if(!canTransitionInquiryStatus(previousStatus,nextStatus)) return { ok:false,status:409,code:'INVALID_STATUS_TRANSITION',message:describeInvalidInquiryTransition(previousStatus,nextStatus) }; if(transitionRequiresNote(previousStatus,nextStatus)&&!note) return { ok:false,status:400,code:'VALIDATION_FAILED',message:'This status transition requires an admin note.',fieldErrors:{note:'Note is required for this status transition.'} }; const now=new Date().toISOString(); await database.prepare('UPDATE inquiries SET status = ?, updated_at = ? WHERE id = ?').bind(nextStatus,now,id).run(); const eid=await createEvent(database,{ inquiryId:id,eventType:'status-changed',createdAt:now,actor:actor(identity),note:note||undefined,metadata:{ previousStatus,nextStatus } }); return { ok:true,data:{ ok:true,inquiryId:id,status:nextStatus,eventId:eid } } }
export async function updateAdminInquiryPriority(env:Env,identity:AccessIdentity,id:string,input:UpdateInquiryPriorityRequest):Promise<MutationResult>{ if(!isPriority(input.priority)) return { ok:false,status:400,code:'VALIDATION_FAILED',message:'Invalid inquiry priority.',fieldErrors:{priority:'Invalid inquiry priority.'} }; const database=db(env); const current=await rowById(database,id); if(!current) return { ok:false,status:404,code:'NOT_FOUND',message:'Inquiry was not found.' }; const previousPriority=toListItem(current).priority; const nextPriority=input.priority; const note=input.note?.trim()||''; const now=new Date().toISOString(); await database.prepare('UPDATE inquiries SET priority = ?, updated_at = ? WHERE id = ?').bind(nextPriority,now,id).run(); const eid=await createEvent(database,{ inquiryId:id,eventType:'priority-changed',createdAt:now,actor:actor(identity),note:note||undefined,metadata:{ previousPriority,nextPriority } }); return { ok:true,data:{ ok:true,inquiryId:id,priority:nextPriority,eventId:eid } } }
export async function addAdminInquiryNote(env:Env,identity:AccessIdentity,id:string,input:AddInquiryNoteRequest):Promise<MutationResult>{ const note=input.note?.trim()||''; if(!note) return { ok:false,status:400,code:'VALIDATION_FAILED',message:'Admin note is required.',fieldErrors:{note:'Note is required.'} }; const database=db(env); const current=await rowById(database,id); if(!current) return { ok:false,status:404,code:'NOT_FOUND',message:'Inquiry was not found.' }; const eid=await createEvent(database,{ inquiryId:id,eventType:'note-added',createdAt:new Date().toISOString(),actor:actor(identity),note,metadata:{ source:'admin-review-queue' } }); return { ok:true,data:{ ok:true,inquiryId:id,eventId:eid } } }
