export const INQUIRY_STATUSES = ['new','triaged','in-progress','waiting-reply','closed','spam'] as const
export type InquiryStatus = typeof INQUIRY_STATUSES[number]
export const INQUIRY_PRIORITIES = ['low','normal','high','urgent'] as const
export type InquiryPriority = typeof INQUIRY_PRIORITIES[number]
export const INQUIRY_EVENT_TYPES = ['received','validated','stored','status-changed','priority-changed','note-added','notification-dispatched','notification-failed','reply-drafted','reply-sent-manually','marked-spam','closed'] as const
export type InquiryEventType = typeof INQUIRY_EVENT_TYPES[number]
export type AdminInquiryListQuery = { limit:number; offset:number; status?:InquiryStatus|'all'; priority?:InquiryPriority|'all'; category?:string; search?:string }
export type AdminInquiryListItem = { id:string; createdAt:string; updatedAt:string; receivedAt:string; status:InquiryStatus; priority:InquiryPriority; category:string; nickname?:string; email?:string; title:string; relatedProductSlug?:string; sourcePath?:string }
export type AdminInquiryEvent = { id:string; inquiryId:string; createdAt:string; eventType:InquiryEventType; note?:string; actor?:string; metadataJson?:string }
export type AdminInquiryDetail = AdminInquiryListItem & { message:string; sourceUrl?:string; clientFingerprint?:string; userAgent?:string; payloadJson:string; events:AdminInquiryEvent[] }
export type AdminInquiryErrorCode = 'UNAUTHORIZED'|'FORBIDDEN'|'NOT_FOUND'|'VALIDATION_FAILED'|'INVALID_STATUS_TRANSITION'|'SERVER_ERROR'
export type UpdateInquiryStatusRequest = { status:InquiryStatus; note?:string }
export type UpdateInquiryPriorityRequest = { priority:InquiryPriority; note?:string }
export type AddInquiryNoteRequest = { note:string }
export type UpdateInquiryStatusResponse = { ok:true; inquiryId:string; status:InquiryStatus; eventId:string }
export type UpdateInquiryPriorityResponse = { ok:true; inquiryId:string; priority:InquiryPriority; eventId:string }
export type AddInquiryNoteResponse = { ok:true; inquiryId:string; eventId:string }
