import { createHash } from 'node:crypto';

import { compileEasyBody } from './directives.mjs';
import { collectFrontmatter, stringifyFrontmatter } from './frontmatter.mjs';
import { parseEasyMarkdown } from './parser.mjs';

export function createSourceHash(source) {
  return createHash('sha256').update(String(source || ''), 'utf8').digest('hex');
}

export function generatedMarker(sourceName, sourceHash = '') {
  const hashLine = sourceHash ? `\nSOURCE HASH: sha256:${sourceHash}` : '';

  return `<!--\nGENERATED FROM ${sourceName}.${hashLine}\nDo not edit this file directly.\nRun: npm run easy:compile\n-->`;
}

export function normalizeGeneratedOutput(source) {
  return String(source || '').replace(/\r\n/g, '\n').trimEnd();
}

export function hasGeneratedMarker(source) {
  return /GENERATED FROM\s+[^.]+\.easy\.md\./.test(String(source || ''));
}

export function readSourceHashFromGenerated(source) {
  const match = String(source || '').match(/SOURCE HASH:\s*sha256:([a-f0-9]{64})/i);
  return match ? match[1].toLowerCase() : '';
}

export function compileEasyMarkdownSource(source, target) {
  const ast = parseEasyMarkdown(source, target);
  const sourceName = target.sourcePath.split('/').pop();
  const sourceHash = createSourceHash(source);
  const { frontmatter, diagnostics: frontmatterDiagnostics } = collectFrontmatter(ast, target);
  const body = compileEasyBody(ast, target);
  const diagnostics = [
    ...(ast.diagnostics || []),
    ...frontmatterDiagnostics,
    ...body.diagnostics,
  ];

  const output = `${generatedMarker(sourceName, sourceHash)}\n\n${stringifyFrontmatter(frontmatter)}\n\n${body.output}\n`;

  return { output, diagnostics, ast, sourceHash };
}
