<script setup lang="ts">
import { ref, watch } from 'vue'
import type { AdminInquiryDetail, InquiryPriority, InquiryStatus } from '@/types/inquiryAdmin'
import { INQUIRY_PRIORITIES, INQUIRY_STATUSES } from '@/types/inquiryAdmin'
import InquiryEventTimeline from './InquiryEventTimeline.vue'
import InquiryPriorityBadge from './InquiryPriorityBadge.vue'
import InquiryStatusBadge from './InquiryStatusBadge.vue'
import InquiryReplyWorkflowPanel from './InquiryReplyWorkflowPanel.vue'
const props=defineProps<{ inquiry: AdminInquiryDetail | null; loading?: boolean }>()
const emit=defineEmits<{ updateStatus:[status:InquiryStatus,note:string]; updatePriority:[priority:InquiryPriority,note:string]; addNote:[note:string] }>()
const nextStatus=ref<InquiryStatus>('triaged'); const nextPriority=ref<InquiryPriority>('normal'); const note=ref('')
watch(()=>props.inquiry,(value)=>{ if(value){ nextStatus.value=value.status; nextPriority.value=value.priority; note.value='' } },{ immediate:true })
</script>
<template><aside class="detail" aria-label="Inquiry detail panel"><p v-if="loading">Loading detail...</p><p v-else-if="!inquiry" class="empty">Select an inquiry to inspect its private review record.</p><template v-else><div class="heading"><p class="eyebrow">Inquiry Detail</p><h3>{{ inquiry.title }}</h3><div class="badges"><InquiryStatusBadge :status="inquiry.status" /><InquiryPriorityBadge :priority="inquiry.priority" /></div></div><dl><dt>Category</dt><dd>{{ inquiry.category }}</dd><dt>Nickname</dt><dd>{{ inquiry.nickname || '-' }}</dd><dt>Email</dt><dd>{{ inquiry.email || '-' }}</dd><dt>Product</dt><dd>{{ inquiry.relatedProductSlug || '-' }}</dd><dt>Source</dt><dd>{{ inquiry.sourcePath || '-' }} <a v-if="inquiry.sourceUrl" :href="inquiry.sourceUrl" target="_blank" rel="noreferrer">open external</a></dd></dl><section><h4>Message</h4><p class="message">{{ inquiry.message }}</p></section><section class="debug"><h4>Debug payload</h4><details><summary>Show payload_json / user agent / fingerprint</summary><pre>{{ inquiry.payloadJson }}</pre><p>User agent: {{ inquiry.userAgent || '-' }}</p><p>Fingerprint: {{ inquiry.clientFingerprint || '-' }}</p></details></section><section class="actions"><h4>Admin actions</h4><textarea v-model="note" placeholder="Optional note. Required for reopening closed/spam transitions." /><div class="action-row"><select v-model="nextStatus"><option v-for="status in INQUIRY_STATUSES" :key="status" :value="status">{{ status }}</option></select><button @click="emit('updateStatus', nextStatus, note)">Update status</button></div><div class="action-row"><select v-model="nextPriority"><option v-for="priority in INQUIRY_PRIORITIES" :key="priority" :value="priority">{{ priority }}</option></select><button @click="emit('updatePriority', nextPriority, note)">Update priority</button></div><button class="secondary" @click="emit('addNote', note)">Add note event</button></section><section><h4>Event timeline</h4><InquiryEventTimeline :events="inquiry.events" /></section><InquiryReplyWorkflowPanel :inquiry="inquiry" /></template></aside></template>
<style scoped>.detail{display:grid;gap:20px;padding:22px;border:1px solid rgba(36,31,26,.12);border-radius:24px;background:rgba(255,255,255,.68);box-shadow:0 18px 54px rgba(36,31,26,.06)}.empty{color:rgba(36,31,26,.62)}.eyebrow{margin:0 0 6px;font-size:12px;font-weight:800;letter-spacing:.12em;text-transform:uppercase;color:#8b5d2e}h3{margin:0;font-size:26px;line-height:1.1}.badges,.action-row{display:flex;gap:10px;align-items:center;flex-wrap:wrap}dl{display:grid;grid-template-columns:110px 1fr;gap:8px 14px}dt{font-size:12px;font-weight:800;text-transform:uppercase;color:rgba(36,31,26,.55)}dd{margin:0;color:rgba(36,31,26,.82)}h4{margin:0 0 8px}.message{white-space:pre-wrap;line-height:1.7;padding:14px;border-radius:16px;background:rgba(255,248,230,.68)}textarea{width:100%;min-height:84px;border:1px solid rgba(36,31,26,.16);border-radius:14px;padding:12px;resize:vertical;background:rgba(255,255,255,.82)}select{min-height:38px;border:1px solid rgba(36,31,26,.16);border-radius:12px;background:white;padding:0 10px}button{min-height:38px;border:0;border-radius:13px;background:#241f1a;color:white;font-weight:800;cursor:pointer}.secondary{background:#8b5d2e}pre{overflow:auto;padding:12px;border-radius:14px;background:rgba(36,31,26,.08)}</style>
