export const INQUIRY_STATUSES = ['new','triaged','in-progress','waiting-reply','closed','spam'] as const
export type InquiryStatus = typeof INQUIRY_STATUSES[number]
export const INQUIRY_PRIORITIES = ['low','normal','high','urgent'] as const
export type InquiryPriority = typeof INQUIRY_PRIORITIES[number]
export type InquiryEventType = 'received'|'validated'|'stored'|'status-changed'|'priority-changed'|'note-added'|'notification-dispatched'|'notification-failed'|'reply-drafted'|'reply-sent-manually'|'marked-spam'|'closed'
export type AdminInquiryListQuery = { status?:InquiryStatus|'all'; priority?:InquiryPriority|'all'; category?:string; search?:string; limit?:number; offset?:number }
export type AdminInquiryListItem = { id:string; createdAt:string; updatedAt:string; receivedAt:string; status:InquiryStatus; priority:InquiryPriority; category:string; nickname?:string; email?:string; title:string; relatedProductSlug?:string; sourcePath?:string }
export type AdminInquiryEvent = { id:string; inquiryId:string; createdAt:string; eventType:InquiryEventType; note?:string; actor?:string; metadataJson?:string }
export type AdminInquiryDetail = AdminInquiryListItem & { message:string; sourceUrl?:string; clientFingerprint?:string; userAgent?:string; payloadJson:string; events:AdminInquiryEvent[] }
export type UpdateInquiryStatusRequest = { status:InquiryStatus; note?:string }
export type UpdateInquiryPriorityRequest = { priority:InquiryPriority; note?:string }
export type AddInquiryNoteRequest = { note:string }
